"""
Central configuration for the AI weather station project.

Team 7 - Weather Station (ESP32 + DHT22 + BMP180)
Everything that might need changing lives here, not in the scripts.
"""

from pathlib import Path

# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
MODEL_DIR = PROJECT_ROOT / "models"
RESULTS_DIR = PROJECT_ROOT / "results"

for _d in (DATA_DIR, MODEL_DIR, RESULTS_DIR):
    _d.mkdir(exist_ok=True)

# --------------------------------------------------------------------------
# Training dataset
# --------------------------------------------------------------------------
# Which dataset to train on. Options: "synthetic" | "jena" | "dwd" | "generic"
#
#   synthetic -> data/weather_synthetic.csv  (generated by src/make_testdata.py)
#                Only for smoke-testing the pipeline. NOT for the paper.
#   jena      -> Max-Planck-Institut fuer Biogeochemie, Jena. 10-min resolution,
#                columns include T (degC), rh (%), p (mbar) -> exact match for
#                DHT22 + BMP180. This is the recommended dataset.
#   dwd       -> Deutscher Wetterdienst hourly station data (Open Data).
#                Temperature + humidity in the "TU" product, pressure in "P0".
DATASET = "jena"

DATASET_FILES = {
    "synthetic": DATA_DIR / "weather_synthetic.csv",
    "jena": DATA_DIR / "jena_climate_2009_2016.csv",
    "dwd": DATA_DIR / "dwd_stuttgart.csv",
    "generic": DATA_DIR / "weather.csv",
}

# How each raw dataset maps onto our unified schema.
# Unified schema = the three quantities our hardware can actually measure.
DATASET_SPECS = {
    "synthetic": {
        "sep": ",",
        "time_col": "timestamp",
        "time_format": None,  # ISO -> pandas can infer
        "columns": {
            "temperature": "temperature",
            "humidity": "humidity",
            "pressure": "pressure",
            "temperature_bmp": "temperature_bmp",
        },
    },
    "jena": {
        "sep": ",",
        "time_col": "Date Time",
        "time_format": "%d.%m.%Y %H:%M:%S",
        "columns": {
            "T (degC)": "temperature",
            "rh (%)": "humidity",
            "p (mbar)": "pressure",
        },
    },
    "dwd": {
        "sep": ";",
        "time_col": "MESS_DATUM",
        "time_format": "%Y%m%d%H",
        "columns": {
            "TT_TU": "temperature",
            "RF_TU": "humidity",
            "P": "pressure",
        },
    },
    "generic": {
        "sep": ",",
        "time_col": "timestamp",
        "time_format": None,
        "columns": {
            "temperature": "temperature",
            "humidity": "humidity",
            "pressure": "pressure",
        },
    },
}

# The three quantities our sensors deliver. A training dataset MUST provide
# these and nothing else may enter the model - otherwise the trained model
# expects inputs the ESP32 cannot produce at inference time.
BASE_COLUMNS = ["temperature", "humidity", "pressure"]

# --------------------------------------------------------------------------
# Resampling and forecast horizon
# --------------------------------------------------------------------------
RESAMPLE = "10min"        # unified time grid for training data
STEP_MINUTES = 10         # must match RESAMPLE
FORECAST_HORIZON_MIN = 60  # predict temperature 60 minutes ahead
TARGET = "temperature"

# --------------------------------------------------------------------------
# Feature engineering
# --------------------------------------------------------------------------
# Lags in minutes: what the value was N minutes ago.
LAGS_MIN = [10, 30, 60, 180, 360]

# Tendencies in minutes: current value minus value N minutes ago.
# The 180/360 min pressure tendency is the classic synoptic forecast predictor:
# falling pressure over 3-6 h announces an approaching front.
TENDENCY_MIN = [10, 60, 180, 360]

# Rolling statistics windows in minutes.
ROLLING_MIN = [60, 360, 1440]

# Drop absolute pressure levels and keep only altitude-invariant pressure
# features (anomaly against own 24h mean, tendencies, variability).
# Set to False only if training data and station are at the same altitude.
ALTITUDE_INVARIANT_PRESSURE = True

# --------------------------------------------------------------------------
# Model training
# --------------------------------------------------------------------------
TEST_SIZE = 0.2          # chronological split - never shuffle time series
RANDOM_STATE = 42

RF_PARAMS = dict(n_estimators=100, min_samples_leaf=8, max_features=0.4, n_jobs=-1,
                 random_state=RANDOM_STATE)
HGB_PARAMS = dict(max_iter=400, learning_rate=0.06, max_depth=None,
                  random_state=RANDOM_STATE)

# --------------------------------------------------------------------------
# Anomaly detection
# --------------------------------------------------------------------------
IFOREST_PARAMS = dict(n_estimators=200, contamination=0.03,
                      random_state=RANDOM_STATE, n_jobs=-1)

# --------------------------------------------------------------------------
# Sensor cross-check (DHT22 vs BMP180)
# --------------------------------------------------------------------------
# Two independent sensors measure temperature at the same place. A sustained
# divergence is a hardware fault, not weather.
CROSSCHECK = dict(
    mad_k=6.0,           # threshold = median + k * MAD of the difference
    min_abs_delta=2.0,   # never flag below this many degrees (noise floor)
    expected_bmp_offset=0.35,  # BMP180 temperature is typically this much warmer
    persistence=6,       # must persist this many samples before flagging
    flatline_window=18,  # samples with zero variance -> stuck sensor
)

# --------------------------------------------------------------------------
# ThingSpeak (live inference only - never used for training)
# --------------------------------------------------------------------------
THINGSPEAK = dict(
    channel_id="3448191",
    read_api_key="",   # leave empty string if channel is public
    results=800,                        # how many recent points to fetch
    field_map={
        "field1": "temperature",      # DHT22
        "field2": "humidity",         # DHT22
        "field3": "temperature_bmp",  # BMP180 - cross-check only
        "field5": "pressure",         # BMP180
    },
    # Optional: write predictions back to a second channel
    write_channel_id="3451792",
    write_api_key="QLR5294N5UEDRROP", 
    write_channel_fields={
        "field1": "forecast_temperature",
        "field2": "anomaly_flag",
        "field3": "sensor_fault_flag",
    },
)
